import type { ITasksColumn } from '~/types/tasks/tasks';

export default defineEventHandler(() => {
    const columns: ITasksColumn[] = [
        {
            id: 'column-1',
            title: 'Backlog',
            order: 0,
            tasks: [
                {
                    id: 'task-1',
                    title: 'Set up project repository',
                    description: 'Initialize the repository and set up GitHub repository with basic structure',
                    image: 'https://placehold.co/600x400/FF5733/FFFFFF/webp',
                    status: 'medium',
                    role: 'dev',
                    assign: ['alice', 'bob'],
                    deadline: new Date('2024-08-15'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-1',
                    order: 0,
                },
                {
                    id: 'task-2',
                    title: 'Design UI wireframes',
                    description: 'Create wireframes for the main user interfaces of the application',
                    image: 'https://placehold.co/700x500/33FF57/FFFFFF/webp',
                    status: 'high',
                    role: 'ux',
                    assign: ['carol'],
                    deadline: new Date('2024-08-20'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-1',
                    order: 1,
                },
                {
                    id: 'task-3',
                    title: 'Write API documentation',
                    description: 'Document all API endpoints and their usage for developers',
                    image: 'https://placehold.co/800x600/3357FF/FFFFFF/webp',
                    status: 'low',
                    role: 'all',
                    assign: ['dave'],
                    deadline: new Date('2024-08-25'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-1',
                    order: 2,
                },
                {
                    id: 'task-4',
                    title: 'Create database schema',
                    description: 'Design and implement the database schema for the project',
                    image: 'https://placehold.co/650x450/FF33A1/FFFFFF/webp',
                    status: 'high',
                    role: 'dev',
                    assign: ['alice'],
                    deadline: new Date('2024-08-18'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-1',
                    order: 3,
                },
            ],
        },
        {
            id: 'column-2',
            title: 'In Progress',
            order: 1,
            tasks: [
                {
                    id: 'task-5',
                    title: 'Develop authentication system',
                    description: 'Implement authentication and authorization for users',
                    image: 'https://placehold.co/700x500/FFB233/FFFFFF/webp',
                    status: 'high',
                    role: 'dev',
                    assign: ['bob'],
                    deadline: new Date('2024-08-30'),
                    doing: new Date('2024-08-05'),
                    review: undefined,
                    done: undefined,
                    columnId: 'column-2',
                    order: 0,
                },
                {
                    id: 'task-6',
                    title: 'Design landing page',
                    description: 'Create and implement the design for the landing page of the application',
                    image: 'https://placehold.co/800x600/33FF9A/FFFFFF/webp',
                    status: 'medium',
                    role: 'ux',
                    assign: ['carol'],
                    deadline: new Date('2024-08-28'),
                    doing: new Date('2024-08-08'),
                    review: undefined,
                    done: undefined,
                    columnId: 'column-2',
                    order: 1,
                },
                {
                    id: 'task-7',
                    title: 'Implement payment gateway',
                    description: 'Integrate payment gateway for processing transactions',
                    image: 'https://placehold.co/600x400/AA33FF/FFFFFF/webp',
                    status: 'high',
                    role: 'dev',
                    assign: ['alice', 'bob'],
                    deadline: new Date('2024-08-25'),
                    doing: new Date('2024-08-12'),
                    review: undefined,
                    done: undefined,
                    columnId: 'column-2',
                    order: 2,
                },
            ],
        },
        {
            id: 'column-3',
            title: 'Completed',
            order: 2,
            tasks: [
                {
                    id: 'task-8',
                    title: 'Setup development environment',
                    description: 'Configure the local development environment for all team members',
                    image: 'https://placehold.co/650x450/33FF57/FFFFFF/webp',
                    status: 'low',
                    role: 'dev',
                    assign: ['dave'],
                    deadline: new Date('2024-08-05'),
                    doing: undefined,
                    review: new Date('2024-08-06'),
                    done: new Date('2024-08-07'),
                    columnId: 'column-3',
                    order: 0,
                },
                {
                    id: 'task-9',
                    title: 'Review project requirements',
                    description: 'Conduct a review meeting to finalize the project requirements',
                    image: 'https://placehold.co/800x600/FF5733/FFFFFF/webp',
                    status: 'medium',
                    role: 'all',
                    assign: ['carol', 'dave'],
                    deadline: new Date('2024-08-10'),
                    doing: undefined,
                    review: new Date('2024-08-11'),
                    done: new Date('2024-08-12'),
                    columnId: 'column-3',
                    order: 1,
                },
            ],
        },
        {
            id: 'column-4',
            title: 'On Hold',
            order: 3,
            tasks: [
                {
                    id: 'task-10',
                    title: 'Evaluate new technologies',
                    description: 'Research and evaluate new technologies for potential use in the project',
                    image: 'https://placehold.co/800x600/FF33A1/FFFFFF/webp',
                    status: 'low',
                    role: 'all',
                    assign: ['bob', 'carol'],
                    deadline: new Date('2024-08-22'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-4',
                    order: 0,
                },
                {
                    id: 'task-11',
                    title: 'Prepare project proposal',
                    description: 'Draft and prepare the project proposal for client presentation',
                    image: 'https://placehold.co/600x400/33FF57/FFFFFF/webp',
                    status: 'medium',
                    role: 'all',
                    assign: ['alice'],
                    deadline: new Date('2024-08-18'),
                    doing: undefined,
                    review: undefined,
                    done: undefined,
                    columnId: 'column-4',
                    order: 1,
                },
            ],
        },
    ];

    return new Promise((res) => {
        setTimeout(() => {
            res(columns);
        }, 1000);
    });
});
